version: '3'
services:
    server:
        env_file: .env
        container_name: 'nodejs_api'
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE: production
                PORT: 5000
        environment:
            - 'PORT=5000'
        ports:
            - '5000:5000'
        restart: 'always'
        command: npm run start
