name: E2E Tests

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: Build the server
            uses: actions/checkout@v1
            uses: actions/setup-node@v2
            with:
                node-version: '12'
          - run: npm install
          - run: npm run build
    test:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Run Tests on the server
        - run: npm run test
