name: E2E Tests

on:
    pull_request:
        branches: [main, develop]

jobs:
    integration:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Setup the node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
             - run: npm install
             - run: npm run build
             - run: npm run test
               env:
                  CI: true
