name: E2E Tests

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    integration:
      runs-on: ubuntu-latest
      steps:
          - name: Build the server
            uses: actions/checkout@v1
            uses: actions/setup-node@v1
            with:
                node-version: '12'
          - run: npm install --quiet
          - run: npm run build
          - run: npm run test
