name: K6 Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    smoke:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run k6 smoke test
              uses: k6io/action@v0.1
              with:
                  filename: tests/smoke.js
    load:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run k6 smoke test
              uses: k6io/action@v0.1
              with:
                  filename: tests/load.js
    stress:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run k6 smoke test
              uses: k6io/action@v0.1
              with:
                  filename: tests/stress.js
    spike:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run k6 smoke test
              uses: k6io/action@v0.1
              with:
                  filename: tests/spike.js
