name: k6 cloud test run
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run k6 cloud test
              uses: k6io/action@v0.1
              with:
                  filename: tests/test.js
                  cloud: true
                  token: ${{ secrets.K6_CLOUD_API_TOKEN }}
