name: K6 Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    metrics:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run k6 smoke test
              uses: k6io/action@v0.1
              with:
                  filename: tests/metrics/smoke.js
            - name: Run k6 load test
              uses: k6io/action@v0.1
              with:
                  filename: tests/metrics/load.js
            - name: Run k6 stress test
              uses: k6io/action@v0.1
              with:
                  filename: tests/metrics/stress.js
            - name: Run k6 spike test
              uses: k6io/action@v0.1
              with:
                  filename: tests/metrics/spike.js
